name: last-build
description: 'Create new OW release on GitHub and upload snapshot archive'
inputs:
  arch:
    description: 'run-time platform'
    required: false
    default: ''
    type: string
  fullname:
    description: 'release asset full file name'
    required: false
    default: ''
    type: string
  tools:
    description: 'used compiler toolchain'
    required: false
    default: ''
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - name: Setup curl options
    id: curlcmd
    uses: "./.github/actions/curlcmd"
  - id: cireldata
    run: |
      echo "tag=Last-CI-build" >> ${{ github.output }}
      echo "timestamp=$(date +'%Y-%m-%d %H:%M:%S')" >> ${{ github.output }}
    shell: bash
  - name: Delete old Release
    uses: "./.github/actions/ghreldel"
    with:
      tag:     ${{ steps.cireldata.outputs.tag }}
      owdebug: ${{ inputs.owdebug }}
  - name: Create new Release
    uses: "./.github/actions/ghrelcre"
    id: cinewrel
    with:
      note:    "Last updated ${{ steps.cireldata.outputs.timestamp }} UTC"
      title:   ${{ steps.cireldata.outputs.tag }}
      tag:     ${{ steps.cireldata.outputs.tag }}
      tagmsg:  ${{ steps.cireldata.outputs.timestamp }}
      owdebug: ${{ inputs.owdebug }}
  - run: |
      $name = Split-Path -Path ${{ inputs.fullname }} -Leaf
      $response = ${{ steps.curlcmd.outputs.gh }} -H "Authorization: Bearer ${{ github.token }}" `
      -X POST "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.cinewrel.outputs.id }}/assets?name=$($name)" `
      -H "Content-Type: application/octet-stream" `
      --data-binary `@${{ inputs.fullname }}
      if( '${{ inputs.owdebug }}' -eq '1' ) { $response }
    shell: pwsh
