name: test-boot
description: 'Process test bootstrap build by OW (for test compatibility)'
inputs:
  hostos:
    description: 'host os'
    required: false
    default: ''
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - if: inputs.hostos == 'lnx'
    name: Test Bootstrap OW
    run: |
      env | sort
      ci/buildx.sh
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       'WATCOM'
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: bash
  - if: inputs.hostos == 'nt'
    name: Test Bootstrap OW
    run: |
      set
      ci/buildx.cmd
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       'WATCOM'
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: cmd
