name: curl-command
description: 'handle curl command line common options'

inputs:
  owcurlopts:
    description: 'additional curl options'
    required: false
    default: ''
    type: string
outputs:
  cov:
    description: 'curl command for Coverity site'
    value: ${{ steps.curlcmd.outputs.cov }}
  gh:
    description: 'curl command for GitHub REST API'
    value: ${{ steps.curlcmd.outputs.gh }}
runs:
  using: composite
  steps:
  - name: Setup curl options
    id: curlcmd
    run: |
      $null = Remove-Item -ErrorAction Ignore alias:curl
      $curl_cov = "curl -s ${{ inputs.owcurlopts }}"
      $curl_gh = $curl_cov + ' -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"'
      "cov=$curl_cov" | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
      "gh=$curl_gh" | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
