name: install
description: 'Build OW install component'
inputs:
  target:
    description: 'install component to process'
    required: false
    default: ''
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - uses: "./.github/actions/artfload"
    with:
      hostos:       'lnx'
      gitpath:      'build binbuild'
      artifact:     'build lnx x64 gcc'
      owdebug:      ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfload"
    with:
      hostos:       'lnx'
      gitpath:      'bld setupgui'
      artifact:     'bld setupgui nt x64 vs2019'
      owdebug:      ${{ inputs.owdebug }}
  - uses: "./.github/actions/artfload"
    with:
      hostos:       'lnx'
      gitpath:      'bld setupgui'
      artifact:     'bld setupgui lnx x64 gcc'
      owdebug:      ${{ inputs.owdebug }}
  # load all release binaries
  - uses: "./.github/actions/relload"
    with:
      tools_nt:     'vs2019'
      tools_lnx:    'gcc'
      tools_osx:    'clang'
      owdebug:      ${{ inputs.owdebug }}
  - if: inputs.target == 'snapshot'
    name: Create OW snapshot
    id: owsnapshot
    uses: "./.github/actions/snapshot"
    with:
      hostos:       'lnx'
      gitpath:      'rel'
      owdebug:      ${{ inputs.owdebug }}
  # run build script
  - if: inputs.target != 'snapshot'
    name: Build Installers
    run: ci/buildx.sh gcc
    env:
      OWBUILD_STAGE: 'inst'
      OWTOOLS:       'GCC'
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWINSTTARGET:  ${{ inputs.target }}
      OWVERBOSE:     1
    shell: bash
  # save all artifacts for distribution
  # full content of directory, cannot specify files
  - uses: "./.github/actions/artfsave"
    with:
      hostos:       'lnx'
      gitpath:      'distrib ow bin'
      artifact:     "install ${{ inputs.target }}"
      owdebug:      ${{ inputs.owdebug }}
