parameters:
  arch:     ''
  title:    ''

jobs:
  - job: build${{ parameters.arch }}
    displayName: "${{ parameters.title }}"
    variables:
      ${{ if eq(parameters.arch, 'lnx') }}:
        owtools:      $(owtools_lnx)
        owscript:     $(owscript_lnx)
      ${{ if eq(parameters.arch, 'nt') }}:
        owtools:      $(owtools_nt)
        owscript:     $(owscript_nt)
      ${{ if eq(parameters.arch, 'osx') }}:
        owtools:      $(owtools_osx)
        owscript:     $(owscript_osx)
      owbuild.stage:  build
    pool:
      ${{ if eq(parameters.arch, 'lnx') }}:
        vmImage: $(owimage_lnx)
      ${{ if eq(parameters.arch, 'nt') }}:
        vmImage: $(owimage_nt)
      ${{ if eq(parameters.arch, 'osx') }}:
        vmImage: $(owimage_osx)
    timeoutInMinutes: 90
    steps:
    - template: dosbox.yml
      parameters:
        arch: ${{ parameters.arch }}
    - template: artfload.yml
      parameters:
        arch:       ${{ parameters.arch }}
        ${{ if eq(parameters.arch, 'nt') }}:
          path:     build\$(owobjdir)
        ${{ if in(parameters.arch, 'lnx', 'osx') }}:
          path:     build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
    - template: artfload.yml
      parameters:
        arch:       ${{ parameters.arch }}
        ${{ if eq(parameters.arch, 'nt') }}:
          path:     bld\watcom\$(owobjdir)
        ${{ if in(parameters.arch, 'lnx', 'osx') }}:
          path:     bld/watcom/$(owobjdir)
        artifname:  bld-watcom-${{ parameters.arch }}
    - script: $(owscript)
      displayName: "Build"
    - ${{ if in(parameters.arch, 'lnx', 'nt') }}:
      - template: artfsave.yml
        parameters: 
          arch:         ${{ parameters.arch }}
          path:         rel
          artifname:    rel-${{ parameters.arch }}
      - template: artfsave.yml
        parameters: 
          arch:         ${{ parameters.arch }}
          ${{ if eq(parameters.arch, 'nt') }}:
            path:       bld\setupgui
          ${{ if in(parameters.arch, 'lnx', 'osx') }}:
            path:       bld/setupgui
          artifname:    bld-setupgui-${{ parameters.arch }}
