parameters:
  arch:     ''
  title:    ''
  doctype:  ''

jobs:
  - job: wiki${{ parameters.doctype }}
    displayName: "${{ parameters.title }}"
    variables:
      ${{ if eq(parameters.arch, 'lnx') }}:
        owtools:        $(owtools_lnx)
        owscript:       $(owscript_lnx)
        owwikipathpdf:  $(owroot)/docs/pdf
        owwikipathhtml: $(owroot)/docs/html
      ${{ if eq(parameters.arch, 'nt') }}:
        owtools:        $(owtools_nt)
        owscript:       $(owscript_nt)
        owwikipathpdf:  $(owroot)\docs\pdf
        owwikipathhtml: $(owroot)\docs\html
      ${{ if eq(parameters.doctype, 'dochtml') }}:
        owdoctarget:    wikihtml .and wikihtml .or -- -- docset=wikihtml
      ${{ if eq(parameters.doctype, 'docpdf') }}:
        owdoctarget:    wikipdf .and wikipdf .or -- -- docset=wikipdf
      owbuild.stage:    docs
    pool:
      ${{ if eq(parameters.arch, 'lnx') }}:
        vmImage: $(owimage_lnx)
      ${{ if eq(parameters.arch, 'nt') }}:
        vmImage: $(owimage_nt)
    steps:
    - template: dosbox.yml
      parameters:
        arch: ${{ parameters.arch }}
    - template: artfload.yml
      parameters:
        arch: ${{ parameters.arch }}
        ${{ if eq(parameters.arch, 'nt') }}:
          path: build\$(owobjdir)
          artifname: build-nt
        ${{ if eq(parameters.arch, 'lnx') }}:
          path: build/$(owobjdir)
          artifname: build-lnx
    - script: $(owscript)
      displayName: "Documentation Build"
    - ${{ if eq(parameters.doctype, 'docpdf') }}:
      - task: CopyFiles@2
        displayName: "Copy Artifact Wiki PDF files"
        inputs:
          contents: |
            *.pdf
          sourceFolder: $(owwikipathpdf)
          targetFolder: $(Build.ArtifactStagingDirectory)
          overWrite: true
    - ${{ if eq(parameters.doctype, 'dochtml') }}:
      - task: CopyFiles@2
        displayName: "Copy Artifact Wiki Html files"
        inputs:
          contents: |
            *.bmp
            *.htm
          sourceFolder: $(owwikipathhtml)
          targetFolder: $(Build.ArtifactStagingDirectory)
          overWrite: true
      - ${{ if eq(parameters.arch, 'nt') }}:
        - script: |
            ren $(Build.ArtifactStagingDirectory)\*.htm *.html
          displayName: "Rename Artifact Wiki Html files"
      - ${{ if eq(parameters.arch, 'lnx') }}:
        - script: |
            for x in $(Build.ArtifactStagingDirectory)/*.htm
            do 
              mv "${x}" "${x}l" 
            done
          displayName: "Rename Artifact Wiki Html files"
    - task: PublishPipelineArtifact@1
      displayName: "Save Artifact wiki-${{ parameters.doctype }}"
      inputs: 
        artifactName:   "wiki-${{ parameters.doctype }}"
        path:           $(Build.ArtifactStagingDirectory)
