name: dosbox-instalation
description: 'Install DOSBOX run-time if necessary'
inputs:
  hostos:
    description: 'host os'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - if: inputs.hostos == 'lnx'
    name: Install DOSBOX
    run: |
      for i in {1..3}
      do
        sudo apt update --fix-missing
        sudo apt-get install -y dosbox
        if [ $? = 0 ]; then
          break
        fi
      done
    shell: bash
  - if: inputs.hostos == 'osx'
    name: Install DOSBOX-X
    run: brew install dosbox-x
    shell: bash
