name: CI-Build-nt
run-name: CI workflow Windows
on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      tools:
        required: true
        type: string
      owtools:
        required: true
        type: string
      image:
        required: true
        type: string
      owdebug:
        required: true
        type: string
jobs:
  boot-nt:
    name: Bootstrap
    runs-on: ${{ inputs.image }}
    steps:
    - run: git config --global core.eol lf
    - run: git config --global core.autocrlf input
    - name: checkout
      uses: actions/checkout@v4
    - name: Bootstrap
      uses: "./.github/actions/boot"
      with:
        hostos:     'nt'
        buildcmd:   "ci/buildx.cmd ${{ inputs.tools }}"
        suffix:     "nt ${{ inputs.arch }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ inputs.owdebug }}
  build-nt:
    name: Build
    needs: boot-nt
    runs-on: ${{ inputs.image }}
    timeout-minutes: 120
    steps:
    - run: git config --global core.eol lf
    - run: git config --global core.autocrlf input
    - name: checkout
      uses: actions/checkout@v4
    - name: Build
      uses: "./.github/actions/build"
      with:
        hostos:     'nt'
        buildcmd:   "ci/buildx.cmd ${{ inputs.tools }}"
        suffix:     "nt ${{ inputs.arch }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ inputs.owdebug }}
  docsbuild:
    name: Docs Build
    needs: boot-nt
    runs-on: ${{ inputs.image }}
    timeout-minutes: 90
    strategy:
      matrix:
        include:
        - title: DOS
          doctype: docdos
        - title: OS/2
          doctype: docos2
        - title: NT
          doctype: docnt
        - title: CHM
          doctype: docchm
        - title: PDF
          doctype: docpdf
        - title: WIN
          doctype: docwin
    steps:
    - run: git config --global core.eol lf
    - run: git config --global core.autocrlf input
    - name: checkout
      uses: actions/checkout@v4
    - name: Build
      uses: "./.github/actions/docbuild"
      with:
        hostos:     'nt'
        buildcmd:   "ci/buildx.cmd ${{ inputs.tools }}"
        target:     ${{ matrix.doctype }}
        suffixi:    "nt ${{ inputs.arch }} ${{ inputs.tools }}"
        suffixo:    "${{ matrix.doctype }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ inputs.owdebug }}
  tests-nt:
    name: Tests
    needs: build-nt
    runs-on: ${{ inputs.image }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Tests
      uses: "./.github/actions/tests"
      with:
        hostos:     'nt'
        suffix:     "nt ${{ inputs.arch }} ${{ inputs.tools }}"
  testboot-nt:
    name: Test Bootstrap
    if: inputs.arch == 'x64'
    needs: tests-nt
    runs-on: ${{ inputs.image }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Load Artifact
      uses: "./.github/actions/artfload"
      with:
        hostos:   'nt'
        gitpath:  'rel'
        artifact: "rel nt ${{ inputs.arch }} ${{ inputs.tools }}"
        owdebug:  ${{ inputs.owdebug }}
    - name: Setup new OW
      run: |
        echo ${{github.workspace}}\rel\binnt>> "%GITHUB_PATH%"
        echo WATCOM=${{github.workspace}}\rel>> "%GITHUB_ENV%"
        echo INCLUDE=${{github.workspace}}\rel\h;${{github.workspace}}\rel\h\nt>> "%GITHUB_ENV%"
      shell: cmd
    - name: Test Bootstrap
      uses: "./.github/actions/testboot"
      with:
        hostos:     'nt'
        owdebug:    ${{ inputs.owdebug }}
