name: CI-Build-lnx
run-name: CI workflow Linux
on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      tools:
        required: true
        type: string
      owtools:
        required: true
        type: string
      image:
        required: true
        type: string
      owdebug:
        required: true
        type: string
jobs:
  boot-lnx:
    name: Bootstrap
    runs-on: ${{ inputs.image }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Bootstrap
      uses: "./.github/actions/boot"
      with:
        hostos:     'lnx'
        buildcmd:   "ci/buildx.sh ${{ inputs.tools }}"
        suffix:     "lnx ${{ inputs.arch }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ inputs.owdebug }}
  build-lnx:
    name: Build
    needs: boot-lnx
    runs-on: ${{ inputs.image }}
    timeout-minutes: 120
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build
      uses: "./.github/actions/build"
      with:
        hostos:     'lnx'
        buildcmd:   "ci/buildx.sh ${{ inputs.tools }}"
        suffix:     "lnx ${{ inputs.arch }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ inputs.owdebug }}
  tests-lnx:
    name: Tests
    needs: build-lnx
    runs-on: ${{ inputs.image }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Tests
      uses: "./.github/actions/tests"
      with:
        hostos:     'lnx'
        suffix:     "lnx ${{ inputs.arch }} ${{ inputs.tools }}"
  testboot-lnx:
    name: Test Bootstrap
    needs: tests-lnx
    runs-on: ${{ inputs.image }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Load Artifact
      uses: "./.github/actions/artfload"
      with:
        hostos:   'lnx'
        gitpath:  'rel'
        artifact: "rel lnx ${{ inputs.arch }} ${{ inputs.tools }}"
        owdebug:  ${{ inputs.owdebug }}
    - name: Test Bootstrap
      uses: "./.github/actions/testboot"
      with:
        hostos:     'lnx'
        gitpath:    'rel'
        owdebug:    ${{ inputs.owdebug }}
