name: CI-Build-osx
run-name: CI workflow OSX
on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      tools:
        required: true
        type: string
      relpath:
        required: true
        type: string
      owtools:
        required: true
        type: string
      image:
        required: true
        type: string
      owdebug:
        required: true
        type: string
jobs:
  boot-osx:
    name: Bootstrap
    runs-on: ${{ inputs.image }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Bootstrap
      uses: "./.github/actions/boot"
      with:
        hostos:     'osx'
        buildcmd:   "ci/buildx.sh ${{ inputs.tools }}"
        suffix:     "osx ${{ inputs.arch }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ inputs.owdebug }}
  build-osx:
    name: Build
    needs: boot-osx
    runs-on: ${{ inputs.image }}
    timeout-minutes: 120
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build
      uses: "./.github/actions/build"
      with:
        hostos:     'osx'
        buildcmd:   "ci/buildx.sh ${{ inputs.tools }}"
        relpath:    ${{ inputs.relpath }}
        suffix:     "osx ${{ inputs.arch }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ inputs.owdebug }}
