name: Release-Build-nt
run-name: Release workflow Windows (daily and monthly)
on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      tools:
        required: true
        type: string
      owtools:
        required: true
        type: string
      image:
        required: true
        type: string
      owdebug:
        required: true
        type: string
jobs:
  boot-nt:
    name: Bootstrap
    runs-on: ${{ inputs.image }}
    steps:
    - run: git config --global core.eol lf
    - run: git config --global core.autocrlf input
    - name: checkout
      uses: actions/checkout@v4
    - run: od -N500 -tx1 projects.txt
    - name: Bootstrap
      uses: "./.github/actions/boot"
      with:
        hostos:     'nt'
        buildcmd:   "ci/buildx.cmd ${{ inputs.tools }}"
        suffix:     "nt ${{ inputs.arch }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ inputs.owdebug }}
    - run: git config --list
  build-nt:
    needs: boot-nt
    name: Build
    runs-on: ${{ inputs.image }}
    timeout-minutes: 120
    steps:
    - run: git config --global core.eol lf
    - run: git config --global core.autocrlf input
    - name: checkout
      uses: actions/checkout@v4
    - run: od -N500 -tx1 projects.txt
    - name: Build
      uses: "./.github/actions/build"
      with:
        hostos:     'nt'
        buildcmd:   "ci/buildx.cmd ${{ inputs.tools }}"
        suffix:     "nt ${{ inputs.arch }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ inputs.owdebug }}
    - run: git config --list
  docsbuild:
    needs: boot-nt
    name: Documentation
    runs-on: ${{ inputs.image }}
    timeout-minutes: 90
    strategy:
      matrix:
        include:
        - title: DOS
          doctype: docdos
        - title: OS/2
          doctype: docos2
        - title: NT
          doctype: docnt
        - title: CHM
          doctype: docchm
        - title: PDF
          doctype: docpdf
        - title: WIN
          doctype: docwin
    steps:
    - run: git config --global core.eol lf
    - run: git config --global core.autocrlf input
    - name: checkout
      uses: actions/checkout@v4
    - run: od -N500 -tx1 projects.txt
    - name: Documentation
      uses: "./.github/actions/docbuild"
      with:
        hostos:     'nt'
        buildcmd:   "ci/buildx.cmd ${{ inputs.tools }}"
        target:     ${{ matrix.doctype }}
        suffixi:    "nt ${{ inputs.arch }} ${{ inputs.tools }}"
        suffixo:    "${{ matrix.doctype }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ inputs.owdebug }}
    - run: git config --list
  tests-nt:
    needs: build-nt
    name: Tests
    runs-on: ${{ inputs.image }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Tests
      uses: "./.github/actions/tests"
      with:
        hostos:     'nt'
        suffix:     "nt ${{ inputs.arch }} ${{ inputs.tools }}"
